import React,{useEffect,useState} from 'react';
import {useSelector,useDispatch} from 'react-redux';
import {Link,useNavigate,useLocation} from 'react-router-dom';
import {Search,ShoppingBag,Menu,X,UserRound,ArrowUpRight} from 'lucide-react';
import {logout} from '../store/authSlice';import {clearCart} from '../store/cartSlice';import api from '../axios';
export default function Navbar(){
const cartItems=useSelector(s=>s.cart.items),user=useSelector(s=>s.auth.user),dispatch=useDispatch(),navigate=useNavigate(),location=useLocation();
const [open,setOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState('');
useEffect(()=>{if(!user||user.role!=='client')return;const id=setTimeout(()=>api.post('/paniers/sync',{items:cartItems.filter(i=>i.produit).map(i=>({produit_id:i.produit.id,quantite:i.quantite,prix:i.produit.prix||0}))}).catch(()=>{}),700);return()=>clearTimeout(id)},[cartItems,user]);
useEffect(()=>setOpen(false),[location.pathname]);
const submit=e=>{e.preventDefault();if(search.trim()){navigate('/shop?nom='+encodeURIComponent(search.trim()));setSearchOpen(false)}};
const logoutUser=()=>{dispatch(logout());dispatch(clearCart());navigate('/')};
return <><div className='announcement'>FREE DELIVERY ON ORDERS OVER 900 DH <span>·</span> MOROCCO / WORLDWIDE</div><header className='ma-header'><button className='ma-mobile-toggle' onClick={()=>setOpen(v=>!v)}>{open?<X size={19}/>:<Menu size={19}/>}</button><nav className={open?'ma-nav open':'ma-nav'}>{[['HOME','/'],['SHOP','/shop'],['JOURNAL','/blog'],['ABOUT','/about'],['CONTACT','/contact']].map(x=><Link key={x[0]} to={x[1]}>{x[0]}</Link>)}</nav><Link className='ma-logo' to='/'>LEXIGAM<span>®</span></Link><div className='ma-actions'><button onClick={()=>setSearchOpen(true)} aria-label='Search'><Search size={17}/></button><button onClick={()=>navigate(user?'/dashboard':'/login')} aria-label='Account'><UserRound size={17}/></button><Link to='/cart' aria-label='Bag'><ShoppingBag size={17}/><b>{cartItems.length}</b></Link>{user&&<button className='ma-logout' onClick={logoutUser}>LOGOUT</button>}{(user?.role==='admin'||user?.role==='vendeur')&&<Link className='ma-admin' to={user.role==='admin'?'/admin/dashboard':'/vendor/dashboard'}>STUDIO <ArrowUpRight size={12}/></Link>}</div></header>{searchOpen&&<div className='search-overlay'><button className='search-close' onClick={()=>setSearchOpen(false)}><X/></button><span className='eyebrow'>SEARCH THE ARCHIVE</span><form onSubmit={submit}><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder='Search products, categories...'/><button><ArrowUpRight/></button></form></div>}</>;
}