import React,{useState,useEffect}from'react';
import {useSelector,useDispatch}from'react-redux';
import {useNavigate,Link}from'react-router-dom';
import {clearCart}from'../store/cartSlice';
import api from'../axios';
import {ArrowLeft,ArrowUpRight}from'lucide-react';

export default function Checkout(){
 const {items}=useSelector(s=>s.cart),user=useSelector(s=>s.auth.user),dispatch=useDispatch(),navigate=useNavigate();
 const [step,setStep]=useState(1),[loading,setLoading]=useState(false),[form,setForm]=useState({adresse:'',ville:'',telephone:'',payment_mode:'cash'});
 useEffect(()=>{if(!user)navigate('/login',{state:{from:'/checkout'}})},[user,navigate]);
 const total=items.reduce((a,i)=>a+i.produit.prix*i.quantite,0),change=e=>setForm({...form,[e.target.name]:e.target.value});
 if(!items.length)return <div className="pb-empty"><h1>Your bag is empty.</h1><Link to="/shop" className="pb-btn">BACK TO SHOP</Link></div>;
 const submit=async()=>{setLoading(true);try{const res=await api.post('/commandes',{items:items.map(i=>({id:i.produit.id,quantite:i.quantite})),...form});dispatch(clearCart());navigate('/order-success/'+res.data.commande_id)}catch(e){alert(e.response?.data?.message||e.message)}finally{setLoading(false)}};
 return <div className="pb-checkout"><div className="pb-check-head"><small>LEXIGAM / CHECKOUT / {step} OF 2</small><h1>Complete your order.</h1></div><div className="pb-check-layout"><section className="pb-check-form">{step===1?<><small>01 / DELIVERY</small><h2>Where should we deliver?</h2><label>FULL ADDRESS<input name="adresse" value={form.adresse} onChange={change} placeholder="ADDRESS"/></label><div><label>CITY<input name="ville" value={form.ville} onChange={change} placeholder="CITY"/></label><label>PHONE<input name="telephone" value={form.telephone} onChange={change} placeholder="PHONE"/></label></div><button className="pb-btn" disabled={!form.adresse||!form.ville||!form.telephone} onClick={()=>setStep(2)}>CONTINUE <ArrowUpRight size={15}/></button></>:<><small>02 / PAYMENT</small><h2>Choose payment.</h2><label className="pb-payment"><input type="radio" name="payment_mode" value="cash" checked={form.payment_mode==='cash'} onChange={change}/><span>CASH</span><em>Pay when your order is delivered.</em></label><label className="pb-payment"><input type="radio" name="payment_mode" value="delivery" checked={form.payment_mode==='delivery'} onChange={change}/><span>PAYMENT ON DELIVERY</span><em>Available for eligible delivery zones.</em></label><div className="pb-check-actions"><button onClick={()=>setStep(1)}><ArrowLeft size={14}/> BACK</button><button className="pb-btn" onClick={submit} disabled={loading}>{loading?'PROCESSING':'CONFIRM ORDER'} <ArrowUpRight size={15}/></button></div></>}</section><aside className="pb-order-summary"><small>ORDER SUMMARY</small>{items.map(i=><div key={i.produit.id}><span>{i.produit.nom} × {i.quantite}</span><b>{i.produit.prix*i.quantite} DH</b></div>)}<strong>TOTAL <b>{total} DH</b></strong></aside></div></div>}